# Project: Project1
# Makefile created by Red Panda C++ 3.2.2958

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-pg" "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-O3" "-std=c++11" "-pipe" "-Wall" "-D_DEBUG"
CFLAGS   = $(INCS) "-std=c17" "-g3" "-O3" "-pipe" "-Wall" "-D_DEBUG"
WINDRESFLAGS = 
RES      = Project1_private.res
OBJ      = main.o add.o $(RES)
BIN      = Project1.exe
LINKOBJ  = "main.o" "add.o" "Project1_private.res"
CLEANOBJ = "main.o" "add.o" "Project1_private.res" "Project1.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

Project1.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "Project1.exe" $(LIBS)

main.o: main.c
	$(CC) -c "main.c" -o "main.o" $(CFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

add.o: add.cpp add.h
	$(CXX) -c "add.cpp" -o "add.o" $(CXXFLAGS) 

Project1_private.res: Project1_private.rc 
	$(WINDRES) -i "Project1_private.rc" --input-format=rc -o "Project1_private.res" -O coff $(WINDRESFLAGS) 

